### ISSUE TITLE
[Enhancement] Make the interaction clearer

### ISSUE THREAD

**Issue by zerebos** [Xhylo/HiddenDMList#1]
Either add a dedicated button for collapsing, or have `cursor: pointer;` on hover of the direct messages text.

**Comment by Xhylo** [comment]
## Hello, Zere
That's a great enhancement, I just added the `cursor: pointer;` to the plugin I will work on a specific button and visual looks in the morning. Sure if you've got anything else to suggest, I'm more than happy looking into it and possibly adding it to the plugin.

- Xyhlo
